name: Deploy react
on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t moatazmkhaled/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true moatazmkhaled/react-test npm run test